FROM ubuntu:22.04

RUN apt update \
    && apt install -y \
    software-properties-common

RUN add-apt-repository --yes ppa:kicad/kicad-7.0-releases \
    && apt update \
    && apt install --install-recommends kicad -y
