name: surf

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
       - '**'

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the surf image
      run: make surf
